SELECT DISTINCT ?item ?itemLabel ?country ?countryLabel ?territory ?territoryLabel
WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "de". }
  ?item ?prop wd:Q2766547.
  OPTIONAL {
    ?item wdt:P17 ?countryLabel.   
    ?item wdt:P131 ?territoryLabel.
  }
}
